tclmode

# Generated by Genus(TM) Synthesis Solution 17.11-s014_1, revision 1.245i
# Generated on: Wed Oct 23 15:26:31 CEST 2019 (Wed Oct 23 13:26:31 GMT 2019)

tcl_set_command_name_echo on

set_log_file fv/keccak/rtl_to_fv_map.log -replace

usage -auto -elapse

set_verification_information rtl_fv_map_db

read_implementation_information fv/keccak -revised fv_map

set_parallel_option -threads 4 -license "xl lp gxl lpgxl eco ecogxl" -norelease_license

set env(RC_VERSION)     "17.11-s014_1"
set env(CDN_SYNTH_ROOT) "/eda/cadence/2017-18/RHELx86/GENUS_17.11.000/tools.lnx86"
set CDN_SYNTH_ROOT      "/eda/cadence/2017-18/RHELx86/GENUS_17.11.000/tools.lnx86"
set env(CW_DIR) "/eda/cadence/2017-18/RHELx86/GENUS_17.11.000/tools.lnx86/lib/chipware"
set CW_DIR      "/eda/cadence/2017-18/RHELx86/GENUS_17.11.000/tools.lnx86/lib/chipware"
set env(NCPROTECT_KEYDB) /eda/cadence/2017-18/RHELx86/INCISIVE_15.20.038/kits/VerificationKit/misc/ip_keys

# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both

add_search_path /techfiles_ldap/umc_ksmi_lab/lib -library -both
read_library -liberty -both   /techfiles_ldap/umc_ksmi_lab/lib/cells_typical.lib

set_naming_style rc -golden
set_naming_rule "%s\[%d\]" -instance_array -golden
set_naming_rule "%s_reg" -register -golden
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -instance -golden
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -variable -golden

set_hdl_options -VERILOG_INCLUDE_DIR "incdir:sep:src:cwd"

set_undriven_signal Z -golden

delete_search_path -all -design -golden
add_search_path ./hdl -design -golden
read_design   -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -verilog2k hdl/keccak.v hdl/f_permutation.v hdl/padder.v hdl/padder1.v hdl/rconst2in1.v hdl/round2in1.v
elaborate_design -golden -root {keccak} -rootonly 

read_design -verilog95   -revised -lastmod -noelab fv/keccak/fv_map.v.gz
elaborate_design -revised -root {keccak}

uniquify -all -nolib -golden

report_design_data
report_black_box

set_flatten_model -seq_constant
set_flatten_model -seq_constant_x_to 0
set_flatten_model -nodff_to_dlat_zero
set_flatten_model -nodff_to_dlat_feedback
set_flatten_model -hier_seq_merge

#add_name_alias fv/keccak/fv_map.singlebit.original_name.alias.json.gz -revised
#set_mapping_method -alias -revised
#add_renaming_rule r1alias _reg((\\\[%w\\\])*(/U\\\$%d)*)$ @1 -type dff -both

set_analyze_option -auto

write_hier_compare_dofile hier_tmp1.lec.do -noexact_pin_match -constraint -usage -replace -balanced_extraction -input_output_pin_equivalence -prepend_string " analyze_datapath -module -verbose ; analyze_datapath  -verbose; "
run_hier_compare hier_tmp1.lec.do -dynamic_hierarchy

report_verification -hier -verbose
set_system_mode lec
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
}

write_verification_information
report_verification_information

exit

